# Generated by Django 5.2.10 on 2026-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код для получения'),
        ),
    ]
